/*
 * Copyright 2026 Java Arena contributors.
 * SPDX-License-Identifier: Apache-2.0
 */

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.function.IntPredicate;

/**
 * Writes javaarena/jdk/JdkChars.java: the character classes javac's scanner asks
 * java.lang.Character about, as range tables computed by the JDK that runs this
 * tool (the reference JDK 21, so Unicode 15.0). TeaVM's own Character tables
 * differ (for example CJK ideographs are not letters there).
 *
 * Usage: java tools/GenJdkChars.java <output directory>
 */
public class GenJdkChars {
    public static void main(String[] args) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                /*
                 * Generated by engine/compiler/tools/GenJdkChars.java from Java %s
                 * (Unicode data of java.lang.Character); do not edit.
                 */

                package javaarena.jdk;

                /** java.lang.Character queries used by javac's scanner, answered as JDK 21 does. */
                public final class JdkChars {
                    private JdkChars() {
                    }

                """.formatted(System.getProperty("java.version")));
        table(sb, "JAVA_IDENTIFIER_START", Character::isJavaIdentifierStart);
        table(sb, "JAVA_IDENTIFIER_PART", Character::isJavaIdentifierPart);
        table(sb, "IDENTIFIER_IGNORABLE", Character::isIdentifierIgnorable);
        table(sb, "WHITESPACE", Character::isWhitespace);
        digits(sb);
        sb.append("""
                    /** Same as Character.isJavaIdentifierStart(int). */
                    public static boolean isJavaIdentifierStart(int cp) {
                        return in(JAVA_IDENTIFIER_START, cp);
                    }

                    /** Same as Character.isJavaIdentifierPart(int). */
                    public static boolean isJavaIdentifierPart(int cp) {
                        return in(JAVA_IDENTIFIER_PART, cp);
                    }

                    /** Same as Character.isIdentifierIgnorable(int). */
                    public static boolean isIdentifierIgnorable(int cp) {
                        return in(IDENTIFIER_IGNORABLE, cp);
                    }

                    /** Same as Character.isWhitespace(int). */
                    public static boolean isWhitespace(int cp) {
                        return in(WHITESPACE, cp);
                    }

                    /** Same as Character.digit(int, int). */
                    public static int digit(int cp, int radix) {
                        if (radix < Character.MIN_RADIX || radix > Character.MAX_RADIX) {
                            return -1;
                        }
                        int lo = 0;
                        int hi = DIGIT_START.length - 1;
                        while (lo <= hi) {
                            int mid = (lo + hi) >>> 1;
                            if (DIGIT_START[mid] > cp) {
                                hi = mid - 1;
                            } else if (DIGIT_START[mid] + DIGIT_LENGTH[mid] <= cp) {
                                lo = mid + 1;
                            } else {
                                int value = DIGIT_VALUE[mid] + (cp - DIGIT_START[mid]);
                                return value < radix ? value : -1;
                            }
                        }
                        return -1;
                    }

                    // bounds holds the first code point of each run; runs alternate between
                    // "not in the set" (from 0) and "in the set".
                    private static boolean in(int[] bounds, int cp) {
                        int lo = 0;
                        int hi = bounds.length;
                        while (lo < hi) {
                            int mid = (lo + hi) >>> 1;
                            if (bounds[mid] <= cp) {
                                lo = mid + 1;
                            } else {
                                hi = mid;
                            }
                        }
                        return (lo & 1) == 1;
                    }
                }
                """);
        Path out = Path.of(args[0], "javaarena", "jdk", "JdkChars.java");
        Files.createDirectories(out.getParent());
        Files.writeString(out, sb.toString());
    }

    static void table(StringBuilder sb, String name, IntPredicate p) {
        List<Integer> bounds = new ArrayList<>();
        boolean inside = false;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            if (p.test(cp) != inside) {
                bounds.add(cp);
                inside = !inside;
            }
        }
        array(sb, name, bounds);
    }

    static void digits(StringBuilder sb) {
        List<Integer> start = new ArrayList<>();
        List<Integer> length = new ArrayList<>();
        List<Integer> value = new ArrayList<>();
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            int v = Character.digit(cp, Character.MAX_RADIX);
            if (v < 0) {
                continue;
            }
            int last = start.size() - 1;
            if (last >= 0 && start.get(last) + length.get(last) == cp
                    && value.get(last) + length.get(last) == v) {
                length.set(last, length.get(last) + 1);
            } else {
                start.add(cp);
                length.add(1);
                value.add(v);
            }
        }
        array(sb, "DIGIT_START", start);
        array(sb, "DIGIT_LENGTH", length);
        array(sb, "DIGIT_VALUE", value);
    }

    static void array(StringBuilder sb, String name, List<Integer> values) {
        sb.append("    private static final int[] ").append(name).append(" = {");
        for (int i = 0; i < values.size(); i++) {
            sb.append(i % 12 == 0 ? "\n        " : " ").append("0x").append(Integer.toHexString(values.get(i)))
                    .append(',');
        }
        sb.append("\n    };\n\n");
    }
}
