#!/usr/bin/env python3
"""Generates test/programs/numbers-fold/Main.java: a few thousand floating-point
literals and constant expressions that javac folds at compile time (arithmetic,
remainders, casts, comparisons, string concatenation). Deterministic (seeded)."""
import math
import random
import struct
import sys

rnd = random.Random(20260928)


def dlit():
    kind = rnd.random()
    if kind < 0.15:
        # hex float
        mant = rnd.getrandbits(52)
        exp = rnd.randint(-1022, 1023)
        return "0x1.%013xp%d" % (mant, exp)
    if kind < 0.25:
        return rnd.choice(["0.1", "0.2", "0.3", "1e23", "2e23", "4.9e-324", "5e-324", "2.2250738585072014E-308",
                           "1.7976931348623157E308", "9007199254740993.0", "0.5", "1.05", "2.675", "4.35", "19.99",
                           "123456789.123456789", "1e-5", "1e7", "0.001", "100.0", "3.0", "1e22", "1e21", "8.41e21",
                           "1.00000000000000011102230246251565404236316680908203125", "2.5", "-0.0", "0.0"])
    digits = rnd.randint(1, 20)
    exp = rnd.randint(-330, 308)
    m = str(rnd.randint(10 ** (digits - 1), 10 ** digits - 1))
    lit = m[0] + ("." + m[1:] if len(m) > 1 else ".0") + "e" + str(exp)
    v = float(lit)
    if v == 0.0 or math.isinf(v):
        return dlit()
    return lit


def flit():
    kind = rnd.random()
    if kind < 0.15:
        mant = rnd.getrandbits(23)
        exp = rnd.randint(-126, 127)
        return "0x1.%06xp%df" % (mant << 1, exp)
    if kind < 0.25:
        return rnd.choice(["0.1f", "16777217f", "1.4e-45f", "1.17549435E-38f", "3.4028235e38f", "0.3f", "1.1f",
                           "2.5f", "33554435f", "1e10f", "0.0f", "-0.0f", "7.006493e-46f"])
    digits = rnd.randint(1, 11)
    exp = rnd.randint(-44, 37)
    m = str(rnd.randint(10 ** (digits - 1), 10 ** digits - 1))
    return m[0] + ("." + m[1:] if len(m) > 1 else ".0") + "e" + str(exp) + "f"


def ilit():
    return str(rnd.choice([0, 1, -1, 7, 42, 2147483647, -2147483648, rnd.randint(-10 ** 6, 10 ** 6)]))


def llit():
    return str(rnd.choice([0, 3, -9, 9223372036854775807, rnd.randint(-10 ** 17, 10 ** 17)])) + "L"


def operand():
    r = rnd.random()
    if r < 0.45:
        return dlit()
    if r < 0.8:
        return flit()
    if r < 0.9:
        return ilit()
    return llit()


def expr():
    r = rnd.random()
    a, b = operand(), operand()
    if r < 0.45:
        op = rnd.choice(["+", "-", "*", "/", "%"])
        while op in "/%" and b.rstrip("L") == "0":
            # an integer division by zero is not a constant; it would throw at run time
            b = operand()
        return "(%s %s %s)" % (a, op, b)
    if r < 0.7:
        cast = rnd.choice(["int", "long", "float", "double", "short", "byte", "char"])
        op = rnd.choice(["*", "/", "+"])
        while op == "/" and b.rstrip("L") == "0":
            b = operand()
        inner = a if rnd.random() < 0.6 else "(%s %s %s)" % (a, op, b)
        e = "(%s) %s" % (cast, inner)
        return "(int) " + e if cast == "char" else e
    if r < 0.85:
        op = rnd.choice(["==", "!=", "<", ">=", "<="])
        return "(%s %s %s)" % (a, op, b)
    return "(-(%s))" % a


lines = []
for i in range(2400):
    lines.append('        System.out.println("e%d " + %s);' % (i, expr()))
consts = []
for i in range(300):
    t = rnd.choice(["double", "float"])
    v = dlit() if t == "double" else flit()
    consts.append("    static final %s K%d = %s;" % (t, i, v))
    lines.append('        System.out.println("k%d " + K%d + " " + (K%d * 3) + " " + %s.toString(K%d));'
                 % (i, i, i, "Double" if t == "double" else "Float", i))

out = ["// Generated by engine/compiler/test/gen-fold.py; do not edit.", "public class Main {"]
out += consts
chunk = 150
nparts = (len(lines) + chunk - 1) // chunk
for p in range(nparts):
    out.append("    static void part%d() {" % p)
    out += lines[p * chunk:(p + 1) * chunk]
    out.append("    }")
out.append("    public static void main(String[] args) {")
for p in range(nparts):
    out.append("        part%d();" % p)
out.append("    }")
out.append("}")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
